<?php

/**
 * BaseStypedja
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $typ
 * @property integer $osoby
 * 
 * @method string   getTyp()   Returns the current record's "typ" value
 * @method integer  getOsoby() Returns the current record's "osoby" value
 * @method Stypedja setTyp()   Sets the current record's "typ" value
 * @method Stypedja setOsoby() Sets the current record's "osoby" value
 * 
 * @package    ug
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStypedja extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stypedja');
        $this->hasColumn('typ', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('osoby', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}