<?php

/**
 * BaseStawqka
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $typ
 * @property integer $wartosc
 * 
 * @method string  getTyp()     Returns the current record's "typ" value
 * @method integer getWartosc() Returns the current record's "wartosc" value
 * @method Stawqka setTyp()     Sets the current record's "typ" value
 * @method Stawqka setWartosc() Sets the current record's "wartosc" value
 * 
 * @package    ug
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStawqka extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stawqka');
        $this->hasColumn('typ', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('wartosc', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}