<?php

/**
 * BaseRodzina
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $stpel
 * @property string $immie
 * @property string $nazwisko
 * @property string $miescowosc
 * @property string $kod
 * @property string $ul
 * @property string $dom
 * @property integer $lokal
 * @property string $telefon
 * @property clob $decyzja
 * @property Doctrine_Collection $Osoba
 * @property Doctrine_Collection $Dochud_rodziny
 * 
 * @method integer             getStpel()          Returns the current record's "stpel" value
 * @method string              getImmie()          Returns the current record's "immie" value
 * @method string              getNazwisko()       Returns the current record's "nazwisko" value
 * @method string              getMiescowosc()     Returns the current record's "miescowosc" value
 * @method string              getKod()            Returns the current record's "kod" value
 * @method string              getUl()             Returns the current record's "ul" value
 * @method string              getDom()            Returns the current record's "dom" value
 * @method integer             getLokal()          Returns the current record's "lokal" value
 * @method string              getTelefon()        Returns the current record's "telefon" value
 * @method clob                getDecyzja()        Returns the current record's "decyzja" value
 * @method Doctrine_Collection getOsoba()          Returns the current record's "Osoba" collection
 * @method Doctrine_Collection getDochudRodziny()  Returns the current record's "Dochud_rodziny" collection
 * @method Rodzina             setStpel()          Sets the current record's "stpel" value
 * @method Rodzina             setImmie()          Sets the current record's "immie" value
 * @method Rodzina             setNazwisko()       Sets the current record's "nazwisko" value
 * @method Rodzina             setMiescowosc()     Sets the current record's "miescowosc" value
 * @method Rodzina             setKod()            Sets the current record's "kod" value
 * @method Rodzina             setUl()             Sets the current record's "ul" value
 * @method Rodzina             setDom()            Sets the current record's "dom" value
 * @method Rodzina             setLokal()          Sets the current record's "lokal" value
 * @method Rodzina             setTelefon()        Sets the current record's "telefon" value
 * @method Rodzina             setDecyzja()        Sets the current record's "decyzja" value
 * @method Rodzina             setOsoba()          Sets the current record's "Osoba" collection
 * @method Rodzina             setDochudRodziny()  Sets the current record's "Dochud_rodziny" collection
 * 
 * @package    ug
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRodzina extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rodzina');
        $this->hasColumn('stpel', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('immie', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('nazwisko', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('miescowosc', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('kod', 'string', 6, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 6,
             ));
        $this->hasColumn('ul', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('dom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('lokal', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('telefon', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('decyzja', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Osoba', array(
             'local' => 'id',
             'foreign' => 'rodzinay_id'));

        $this->hasMany('Dochod_rodziny as Dochud_rodziny', array(
             'local' => 'id',
             'foreign' => 'rodzinay_id'));
    }
}