<?php

/**
 * BaseDochod_rodziny
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $rodzinay_id
 * @property string $typ
 * @property float $wartosc
 * @property Rodzina $Rodzina
 * 
 * @method integer        getRodzinayId()  Returns the current record's "rodzinay_id" value
 * @method string         getTyp()         Returns the current record's "typ" value
 * @method float          getWartosc()     Returns the current record's "wartosc" value
 * @method Rodzina        getRodzina()     Returns the current record's "Rodzina" value
 * @method Dochod_rodziny setRodzinayId()  Sets the current record's "rodzinay_id" value
 * @method Dochod_rodziny setTyp()         Sets the current record's "typ" value
 * @method Dochod_rodziny setWartosc()     Sets the current record's "wartosc" value
 * @method Dochod_rodziny setRodzina()     Sets the current record's "Rodzina" value
 * 
 * @package    ug
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDochod_rodziny extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dochod_rodziny');
        $this->hasColumn('rodzinay_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('typ', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('wartosc', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Rodzina', array(
             'local' => 'rodzinay_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}