<?php

/**
 * BaseDochod_osoby
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $osoba_id
 * @property string $typ
 * @property float $wartosc
 * @property Osoba $Osoba
 * 
 * @method integer      getOsobaId()  Returns the current record's "osoba_id" value
 * @method string       getTyp()      Returns the current record's "typ" value
 * @method float        getWartosc()  Returns the current record's "wartosc" value
 * @method Osoba        getOsoba()    Returns the current record's "Osoba" value
 * @method Dochod_osoby setOsobaId()  Sets the current record's "osoba_id" value
 * @method Dochod_osoby setTyp()      Sets the current record's "typ" value
 * @method Dochod_osoby setWartosc()  Sets the current record's "wartosc" value
 * @method Dochod_osoby setOsoba()    Sets the current record's "Osoba" value
 * 
 * @package    ug
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDochod_osoby extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dochod_osoby');
        $this->hasColumn('osoba_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('typ', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('wartosc', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Osoba', array(
             'local' => 'osoba_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}