<?php

/**
 * Dochod_rodzinyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Dochod_rodzinyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Dochod_rodzinyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Dochod_rodziny');
    }
}