<?php

/**
 * Dochod_osobyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Dochod_osobyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Dochod_osobyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Dochod_osoby');
    }
}