<?php

/**
 * OsobaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OsobaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OsobaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Osoba');
    }
}