<?php

/**
 * RodzinaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RodzinaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RodzinaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rodzina');
    }
}