<?php

/**
 * StawqkaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StawqkaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StawqkaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Stawqka');
    }
}