<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/12/14 21:17:45

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ug',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
