<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/12/15 15:57:25

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ug',
  'username' => 'root',
  'password' => NULL,
  'attributes' => 
  array (
    'default_table_charset' => 'utf8',
    'default_table_collate' => 'utf8_general_ci',
  ),
  'name' => 'doctrine',
)),);
