<?php

/**
 * Osoba
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ug
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Osoba extends BaseOsoba
{
public function dochod()
  {
    $q = Doctrine_Query::create()
    ->select('SUM(d.wartosc ) as dochod')
    ->from('dochod_osoby d')
    ->where('d.osoba_id= ?', $this->getId())
    ->fetchArray();
    
    $dochod = $q[0]['dochod'];
    return  $dochod;
  }
  
public function dochodZiemia()
  {
    $z = Doctrine_Query::create()
    ->select('o.ziemia')
    ->from('osoba o')
    ->where('o.id= ?', $this->getId())
    ->fetchArray();
    $ziemia = $z[0]['ziemia'];
    return  $ziemia*250;
  }
}