<?php

/**
 * Rodzina
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ug
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Rodzina extends BaseRodzina
{
  public function liczba_osub()
  {
    $q = Doctrine_Query::create()
    ->select('COUNT(*) AS liczba')
    ->from('osoba')
    ->where('rodzinay_id = ?', $this->getId())
    ->fetchArray();
    return $q[0]['liczba'];
  }
  
  public function liczba_uczniow()
  {
    $q = Doctrine_Query::create()
    ->select('COUNT(*) AS liczba')
    ->from('osoba')
    ->where('rodzinay_id = ? AND typ = "uczen"', $this->getId())
    ->fetchArray();
    return $q[0]['liczba'];
  }
  
  public function uczniowie()
  {
    $q = Doctrine_Query::create()
    ->select('*')
    ->from('osoba')
    ->where('rodzinay_id = ? AND typ = "uczen"', $this->getId())
    ->execute();
    return $q;
  }
  
public function dochod_rodziny()
  {
    $q = Doctrine_Query::create()
    ->select('SUM(d.wartosc ) as dochod')
    ->from('dochod_rodziny d')
    ->where('d.rodzinay_id= ?', $this->getId())
    ->fetchArray();
    
    $dochod = $q[0]['dochod'];
    return  $dochod;
  }
  
  public function dochod()
  {
    $q = Doctrine_Query::create()
    ->select('*')
    ->from('osoba')
    ->where('rodzinay_id = ?', $this->getId());
    $suma = 0;
    $osoby = $q->execute();
    
    foreach ($osoby as $osoba){
        $suma+= $osoba->dochod();
        $suma+= $osoba->dochodZiemia();
    }
    return $suma  + $this->dochod_rodziny();
  }
  
  public function zakres()
  {
    $srednia = $this->dochod() / $this->liczba_osub() ;
    switch($srednia)
    {
        case $srednia>0 AND $srednia<=200: 
                return 1; 
        case $srednia>200 AND $srednia<=400: 
                return 2;
        case $srednia>400 AND $srednia<=600: 
                return 3; 
        case $srednia>600 : 
                return 4;
    }
  }
}